issues = [
    [
        "1",
        "abiencoderv2-array",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#storage-abiencoderv2-array'>Storageabiencoderv2 array</a>",
        "High",
        "High",
    ],
    [
        "2",
        "arbitrary-send-erc20",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#arbitrary-from-in-transferfrom'>transferFromuses arbitrary from</a>",
        "High",
        "High",
    ],
    [
        "3",
        "array-by-reference",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#modifying-storage-array-by-value'>Modifyingstorage array by value</a>",
        "High",
        "High",
    ],
    [
        "4",
        "encode-packed-collision",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#abi-encodePacked-collision'>ABIencodePacked Collision</a>",
        "High",
        "High",
    ],
    [
        "5",
        "incorrect-shift",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#incorrect-shift-in-assembly'>Theorder of parameters in a shift instruction is incorrect.</a>",
        "High",
        "High",
    ],
    [
        "6",
        "multiple-constructors",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#multiple-constructor-schemes'>Multipleconstructor schemes</a>",
        "High",
        "High",
    ],
    [
        "7",
        "name-reused",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#name-reused'>Contract's namereused</a>",
        "High",
        "High",
    ],
    [
        "8",
        "protected-vars",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#protected-variables'>Detectedunprotected variables</a>",
        "High",
        "High",
    ],
    [
        "9",
        "public-mappings-nested",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#public-mappings-with-nested-variables'>Publicmappings with nested variables</a>",
        "High",
        "High",
    ],
    [
        "10",
        "rtlo",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#right-to-left-override-character'>Right-To-Left-Overridecontrol character is used</a>",
        "High",
        "High",
    ],
    [
        "11",
        "shadowing-state",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#state-variable-shadowing'>Statevariables shadowing</a>",
        "High",
        "High",
    ],
    [
        "12",
        "suicidal",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#suicidal'>Functions allowing anyoneto destruct the contract</a>",
        "High",
        "High",
    ],
    [
        "13",
        "uninitialized-state",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#uninitialized-state-variables'>Uninitializedstate variables</a>",
        "High",
        "High",
    ],
    [
        "14",
        "uninitialized-storage",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#uninitialized-storage-variables'>Uninitializedstorage variables</a>",
        "High",
        "High",
    ],
    [
        "15",
        "unprotected-upgrade",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#unprotected-upgradeable-contract'>Unprotectedupgradeable contract</a>",
        "High",
        "High",
    ],
    [
        "16",
        "codex",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#codex'>Use Codex to findvulnerabilities.</a>",
        "High",
        "Low",
    ],
    [
        "17",
        "arbitrary-send-erc20-permit",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#arbitrary-from-in-transferfrom-used-with-permit'>transferFromuses arbitrary from with permit</a>",
        "High",
        "Medium",
    ],
    [
        "18",
        "arbitrary-send-eth",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#functions-that-send-ether-to-arbitrary-destinations'>Functionsthat send Ether to arbitrary destinations</a>",
        "High",
        "Medium",
    ],
    [
        "19",
        "controlled-array-length",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#array-length-assignment'>Taintedarray length assignment</a>",
        "High",
        "Medium",
    ],
    [
        "20",
        "controlled-delegatecall",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#controlled-delegatecall'>Controlleddelegatecall destination</a>",
        "High",
        "Medium",
    ],
    [
        "21",
        "delegatecall-loop",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation/#payable-functions-using-delegatecall-inside-a-loop'>Payablefunctions using delegatecall inside a loop</a>",
        "High",
        "Medium",
    ],
    [
        "22",
        "incorrect-exp",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#incorrect-exponentiation'>Incorrectexponentiation</a>",
        "High",
        "Medium",
    ],
    [
        "23",
        "incorrect-return",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#incorrect-assembly-return'>If areturn is incorrectly used in assembly mode.</a>",
        "High",
        "Medium",
    ],
    [
        "24",
        "msg-value-loop",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation/#msgvalue-inside-a-loop'>msg.valueinside a loop</a>",
        "High",
        "Medium",
    ],
    [
        "25",
        "reentrancy-eth",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#reentrancy-vulnerabilities'>Reentrancyvulnerabilities (theft of ethers)</a>",
        "High",
        "Medium",
    ],
    [
        "26",
        "return-leave",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#incorrect-assembly-return'>If areturn is used instead of a leave.</a>",
        "High",
        "Medium",
    ],
    [
        "27",
        "storage-array",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#storage-signed-integer-array'>Signedstorage integer array compiler bug</a>",
        "High",
        "Medium",
    ],
    [
        "28",
        "unchecked-transfer",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#unchecked-transfer'>Unchecked tokenstransfer</a>",
        "High",
        "Medium",
    ],
    [
        "29",
        "weak-prng",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#weak-PRNG'>Weak PRNG</a>",
        "High",
        "Medium",
    ],
    [
        "30",
        "domain-separator-collision",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#domain-separator-collision'>DetectsERC20 tokens that have a function whose signature collides with EIP-2612's DOMAIN_SEPARATOR()</a>",
        "Medium",
        "High",
    ],
    [
        "31",
        "enum-conversion",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#dangerous-enum-conversion'>Detectdangerous enum conversion</a>",
        "Medium",
        "High",
    ],
    [
        "32",
        "erc20-interface",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#incorrect-erc20-interface'>IncorrectERC20 interfaces</a>",
        "Medium",
        "High",
    ],
    [
        "33",
        "erc721-interface",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#incorrect-erc721-interface'>IncorrectERC721 interfaces</a>",
        "Medium",
        "High",
    ],
    [
        "34",
        "incorrect-equality",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#dangerous-strict-equalities'>Dangerousstrict equalities</a>",
        "Medium",
        "High",
    ],
    [
        "35",
        "locked-ether",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#contracts-that-lock-ether'>Contractsthat lock ether</a>",
        "Medium",
        "High",
    ],
    [
        "36",
        "mapping-deletion",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#deletion-on-mapping-containing-a-structure'>Deletionon mapping containing a structure</a>",
        "Medium",
        "High",
    ],
    [
        "37",
        "shadowing-abstract",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#state-variable-shadowing-from-abstract-contracts'>Statevariables shadowing from abstract contracts</a>",
        "Medium",
        "High",
    ],
    [
        "38",
        "tautological-compare",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#tautological-compare'>Comparing avariable to itself always returns true or false, depending on comparison</a>",
        "Medium",
        "High",
    ],
    [
        "39",
        "tautology",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#tautology-or-contradiction'>Tautologyor contradiction</a>",
        "Medium",
        "High",
    ],
    [
        "40",
        "write-after-write",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#write-after-write'>Unused write</a>",
        "Medium",
        "High",
    ],
    [
        "41",
        "boolean-cst",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#misuse-of-a-boolean-constant'>Misuseof Boolean constant</a>",
        "Medium",
        "Medium",
    ],
    [
        "42",
        "constant-function-asm",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#constant-functions-using-assembly-code'>Constantfunctions using assembly code</a>",
        "Medium",
        "Medium",
    ],
    [
        "43",
        "constant-function-state",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#constant-functions-changing-the-state'>Constantfunctions changing the state</a>",
        "Medium",
        "Medium",
    ],
    [
        "44",
        "divide-before-multiply",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#divide-before-multiply'>Imprecisearithmetic operations order</a>",
        "Medium",
        "Medium",
    ],
    [
        "45",
        "reentrancy-no-eth",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#reentrancy-vulnerabilities-1'>Reentrancyvulnerabilities (no theft of ethers)</a>",
        "Medium",
        "Medium",
    ],
    [
        "46",
        "reused-constructor",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#reused-base-constructors'>Reused baseconstructor</a>",
        "Medium",
        "Medium",
    ],
    [
        "47",
        "tx-origin",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#dangerous-usage-of-txorigin'>Dangeroususage of tx.origin</a>",
        "Medium",
        "Medium",
    ],
    [
        "48",
        "unchecked-lowlevel",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#unchecked-low-level-calls'>Uncheckedlow-level calls</a>",
        "Medium",
        "Medium",
    ],
    [
        "49",
        "unchecked-send",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#unchecked-send'>Unchecked send</a>",
        "Medium",
        "Medium",
    ],
    [
        "50",
        "uninitialized-local",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#uninitialized-local-variables'>Uninitializedlocal variables</a>",
        "Medium",
        "Medium",
    ],
    [
        "51",
        "unused-return",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#unused-return'>Unused returnvalues</a>",
        "Medium",
        "Medium",
    ],
    [
        "52",
        "incorrect-modifier",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#incorrect-modifier'>Modifiers thatcan return the default value</a>",
        "Low",
        "High",
    ],
    [
        "53",
        "shadowing-builtin",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#builtin-symbol-shadowing'>Built-insymbol shadowing</a>",
        "Low",
        "High",
    ],
    [
        "54",
        "shadowing-local",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#local-variable-shadowing'>Localvariables shadowing</a>",
        "Low",
        "High",
    ],
    [
        "55",
        "uninitialized-fptr-cst",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#uninitialized-function-pointers-in-constructors'>Uninitializedfunction pointer calls in constructors</a>",
        "Low",
        "High",
    ],
    [
        "56",
        "variable-scope",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#pre-declaration-usage-of-local-variables'>Localvariables used prior their declaration</a>",
        "Low",
        "High",
    ],
    [
        "57",
        "void-cst",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#void-constructor'>Constructor callednot implemented</a>",
        "Low",
        "High",
    ],
    [
        "58",
        "calls-loop",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation/#calls-inside-a-loop'>Multiple callsin a loop</a>",
        "Low",
        "Medium",
    ],
    [
        "59",
        "events-access",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#missing-events-access-control'>MissingEvents Access Control</a>",
        "Low",
        "Medium",
    ],
    [
        "60",
        "events-maths",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#missing-events-arithmetic'>MissingEvents Arithmetic</a>",
        "Low",
        "Medium",
    ],
    [
        "61",
        "incorrect-unary",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#dangerous-unary-expressions'>Dangerousunary expressions</a>",
        "Low",
        "Medium",
    ],
    [
        "62",
        "missing-zero-check",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#missing-zero-address-validation'>MissingZero Address Validation</a>",
        "Low",
        "Medium",
    ],
    [
        "63",
        "reentrancy-benign",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#reentrancy-vulnerabilities-2'>Benignreentrancy vulnerabilities</a>",
        "Low",
        "Medium",
    ],
    [
        "64",
        "reentrancy-events",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#reentrancy-vulnerabilities-3'>Reentrancyvulnerabilities leading to out-of-order Events</a>",
        "Low",
        "Medium",
    ],
    [
        "65",
        "return-bomb",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#return-bomb'>A low level callee mayconsume all callers gas unexpectedly.</a>",
        "Low",
        "Medium",
    ],
    [
        "66",
        "timestamp",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#block-timestamp'>Dangerous usage ofblock.timestamp</a>",
        "Low",
        "Medium",
    ],
    [
        "67",
        "assembly",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#assembly-usage'>Assembly usage</a>",
        "Informational",
        "High",
    ],
    [
        "68",
        "assert-state-change",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#assert-state-change'>Assert statechange</a>",
        "Informational",
        "High",
    ],
    [
        "69",
        "boolean-equal",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#boolean-equality'>Comparison toboolean constant</a>",
        "Informational",
        "High",
    ],
    [
        "70",
        "cyclomatic-complexity",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#cyclomatic-complexity'>Detectsfunctions with high (&gt; 11) cyclomatic complexity</a>",
        "Informational",
        "High",
    ],
    [
        "71",
        "deprecated-standards",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#deprecated-standards'>DeprecatedSolidity Standards</a>",
        "Informational",
        "High",
    ],
    [
        "72",
        "erc20-indexed",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#unindexed-erc20-event-parameters'>Un-indexedERC20 event parameters</a>",
        "Informational",
        "High",
    ],
    [
        "73",
        "function-init-state",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#function-initializing-state'>Functioninitializing state variables</a>",
        "Informational",
        "High",
    ],
    [
        "74",
        "incorrect-using-for",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#incorrect-using-for-usage'>Detectsusing-for statement usage when no function from a given library matches a given type</a>",
        "Informational",
        "High",
    ],
    [
        "75",
        "low-level-calls",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#low-level-calls'>Low level calls</a>",
        "Informational",
        "High",
    ],
    [
        "76",
        "missing-inheritance",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#missing-inheritance'>Missinginheritance</a>",
        "Informational",
        "High",
    ],
    [
        "77",
        "naming-convention",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#conformance-to-solidity-naming-conventions'>Conformityto Solidity naming conventions</a>",
        "Informational",
        "High",
    ],
    [
        "78",
        "pragma",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#different-pragma-directives-are-used'>Ifdifferent pragma directives are used</a>",
        "Informational",
        "High",
    ],
    [
        "79",
        "redundant-statements",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#redundant-statements'>Redundantstatements</a>",
        "Informational",
        "High",
    ],
    [
        "80",
        "solc-version",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#incorrect-versions-of-solidity'>IncorrectSolidity version</a>",
        "Informational",
        "High",
    ],
    [
        "81",
        "unimplemented-functions",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#unimplemented-functions'>Unimplementedfunctions</a>",
        "Informational",
        "High",
    ],
    [
        "82",
        "unused-state",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#unused-state-variable'>Unused statevariables</a>",
        "Informational",
        "High",
    ],
    [
        "83",
        "costly-loop",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#costly-operations-inside-a-loop'>Costlyoperations in a loop</a>",
        "Informational",
        "Medium",
    ],
    [
        "84",
        "dead-code",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#dead-code'>Functions that are notused</a>",
        "Informational",
        "Medium",
    ],
    [
        "85",
        "reentrancy-unlimited-gas",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#reentrancy-vulnerabilities-4'>Reentrancyvulnerabilities through send and transfer</a>",
        "Informational",
        "Medium",
    ],
    [
        "86",
        "similar-names",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#variable-names-too-similar'>Variablenames are too similar</a>",
        "Informational",
        "Medium",
    ],
    [
        "87",
        "too-many-digits",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#too-many-digits'>Conformance tonumeric notation best practices</a>",
        "Informational",
        "Medium",
    ],
    [
        "88",
        "cache-array-length",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#cache-array-length'>Detectsfor loops that use length member of some storage array in their loop conditionand don't modify it.</a>",
        "Optimization",
        "High",
    ],
    [
        "89",
        "constable-states",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#state-variables-that-could-be-declared-constant'>Statevariables that could be declared constant</a>",
        "Optimization",
        "High",
    ],
    [
        "90",
        "external-function",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#public-function-that-could-be-declared-external'>Publicfunction that could be declared external</a>",
        "Optimization",
        "High",
    ],
    [
        "91",
        "immutable-states",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#state-variables-that-could-be-declared-immutable'>Statevariables that could be declared immutable</a>",
        "Optimization",
        "High",
    ],
    [
        "92",
        "var-read-using-this",
        "<a href='https://github.com/crytic/slither/wiki/Detector-Documentation#public-variable-read-in-external-context'>Contractreads its own variable using this</a>",
        "Optimization",
        "High",
    ],

];

module.exports = {
    issues,
};